version: '3.1'

#volumes:
#  postgresql_data:
#    driver: local

services:
  kafka:
    image: bitnami/kafka:3.4.0
    restart: always
    ports:
      - 9092:9092
      
    environment:
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes	
  app:
    image: demo:0.0.1-SNAPSHOT
     
  
  
  #  magic:
  #    image: digitsy/kafka-magic:4.0.1.138
  #    restart: always
  #    ports:
  #      - "8020:80"
  #    environment:
  #      KMAGIC_ALLOW_TOPIC_DELETE: "false"
  #    depends_on:
  # #      - kafka
  # redis:
    # image: redis:alpine
    # restart: always
    # hostname: redis
    # ports:
      # - "6379:6379"
# #  postgresql:
#    image: docker.io/bitnami/postgresql:latest
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#      - POSTGRESQL_USERNAME=bn_keycloak
#      - POSTGRESQL_DATABASE=bitnami_keycloak
#    volumes:
#      - 'postgresql_data:/bitnami/postgresql'
    #  keycloak:
    #    image: docker.io/bitnami/keycloak:latest
    #    ports:
    #      - "8080:8080"
    #    environment:
    #      - KEYCLOAK_CREATE_ADMIN_USER=true
    #    depends_on:
    #      - postgresql

  # postgresql:
    # image: postgres:14
    # container_name: local_pgdb
    # restart: always
    # ports:
      # - "5432:5432"
    # environment:
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: postgres
    # volumes:
      # - local_pgdata:/var/lib/postgresql/data
  # pgadmin:
    # image: dpage/pgadmin4
    # container_name: pgadmin4_container
    # restart: always
    # ports:
      # - "8888:80"
    # environment:
      # PGADMIN_DEFAULT_EMAIL: pgadmin@aselsan.com
      # PGADMIN_DEFAULT_PASSWORD: pgadmin
    # volumes:
      # - pgadmin-data:/var/lib/pgadmin
# volumes:
  # local_pgdata:
  # pgadmin-data: